config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles #, only: [:show, :index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable
  has_many :articles
  
  validates :username, presence: true, length: { minimum: 3, maximum: 16}, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
        keys: [:email, :username, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:sign_in,
        keys: [:email, :username, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:account_update,
          keys: [:email, :username, :password, :password_confirmation])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
    
  def show
    # byebug
    # @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
     # @article = Article.find(params[:id])
  end

  def create
    # render plain: params[:article]
    @article = Article.new(article_params.merge(user_id: current_user.id))
    if @article.save
      # flash[:notice] = "Article added successfully."
      render json: {
        notice: 'Article created successfully'
      }, status: 200
    else
      # flash[:alert] = @article.errors.full_messages
      render json: {
        errors: @article.errors.full_messages
      }, status: 400
    end   
  end

  def update
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    # @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private 

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

    def about
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_active_nav_item(action)       
    params[:action] == action ? "active" : nil        
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors' %>
<%= form_with(model: @article, local: true) do |f| %>
    <div class="form-group row">
        <%= f.label :title, class: "col-2 col-form-label" %>
        <div class="col-10">
            <%= f.text_field :title, class: "form-control", placeholder: "Title of article" %>
        </div>
    </div>
    <div class="form-group row">
        <%= f.label :description, class: "col-2 col-form-label" %>
        <div class="col-10">
            <%= f.text_area :description, rows: 4, class: "form-control", placeholder: "Description of article" %>
        </div>
    </div>
    <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-violet text-white mr-3" %>
        <%= link_to 'Cancel', articles_path, class: "btn btn-secondary" %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
    <h1 class="text-center">Edit Article</h1>

    <%= render 'form' %>  
</div>

app/views/articles/index.html.erb
<article-index
  :articles="<%= @articles.to_json %>"
></article-index>

app/views/articles/new.html.erb
<div class="container">
    <h1 class="text-center">Create a new Article</h1>

    <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container">
    <h1>Artile details</h1>
    <div class="media position-relative">
        <svg class="bd-placeholder-img mr-3" width="250" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Generic placeholder image:  " preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Generic placeholder image</title>
            <rect width="100%" height="100%" fill="#6c757d"></rect>
            <text x="50%" y="50%" fill="#dee2e6" dy=".3em"> </text>
        </svg>
        <div class="media-body">
            <h5 class="mt-0"><%= @article.title %></h5>
            <p><%= simple_format(@article.description) %></p>            
        </div>
    </div>                
    <div class="d-flex flex-row-reverse bd-highlight">
        <div class="p-2 bd-highlight"><%= link_to 'Back', articles_path, class: "btn btn-secondary btn-lg" %></div>
        <div class="p-2 bd-highlight"><%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-lg" %></div>
        <div class="p-2 bd-highlight"><%= link_to 'Edit', edit_article_path(@article), class: "btn btn-primary btn-lg" %></div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="mt-auto py-4 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy; 2022 <%= link_to "Dmitrii Cherkasov", "https://github.com/HeliotropicAfterglow/", class: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>    
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ADS Project", root_path, class: "navbar-brand",  id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%=is_active_nav_item('home')%>">
        <% if current_page?(root_path) %>
        <%=   link_to ("Home <span class='sr-only'>(current)</span>").html_safe, root_path, class: "nav-link" %>
        <% else %>
        <%=   link_to "Home", root_path, class: "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item <%=is_active_nav_item('index')%>">
        <% if current_page?(articles_path) %>
        <%=   link_to ("Articles <span class='sr-only'>(current)</span>").html_safe, articles_path, class: "nav-link" %>
        <% else %>
        <%=   link_to "Articles", articles_path, class: "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item <%=is_active_nav_item('about')%>">
        <% if current_page?(about_path) %>
        <%=   link_to ("About <span class='sr-only'>(current)</span>").html_safe, about_path, class: "nav-link" %>
        <% else %>
        <%=   link_to "About", about_path, class: "nav-link" %>
        <% end %>
      </li>
      <% if user_signed_in? %>         
        <li class="nav-item">
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Logged in as <strong><%= current_user.username%></strong> </a>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
        </li>
      <% end %>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <%= link_to 'Create new article', new_article_path, class: "btn btn-violet text-white mr-3" %>
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Articles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <div data-behavior="vue">
      <v-app>
        <%= render 'layouts/navigation' %>
        <!--%= render 'layouts/messages' %-->
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
        <%= render 'layouts/footer' %>
      </v-app>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <h1>This is the About page</h1>
</div>

app/views/pages/home.html.erb
<div class="container" id="home-container">
    <div class="jumbotron">
        <h1 class="display-4">ADS Project</h1>
        <p class="lead">Placeholder</p>
        <hr class="my-4">
        <p>Placeholder</p>
        <%= link_to 'Articles listing', articles_path, class: "btn btn-primary btn-lg" %>
    </div>   
</div>

app/views/shared/_errors.html.erb
<% if @article.errors.any? %>
    <div class="row justify-content-center">
        <div class="alert alert-danger alert-dismissible fade show col-8" role="alert">
            <h4 class="alert-heading">The following errors prevented the article from being saved!</h4>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <ul>
                <% @article.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div> 
    </div>       
<% end %>